---
title: "CA_WILDFIRE_PLOTS"
author: "Michael Mann"
date: "January 31, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(cache=T)
knitr::opts_chunk$set(echo = T)
library(raster)
library(sf)
library(ggplot2)
library(rasterVis)
library(tools)
library(dplyr)
library(reshape2)
library(rmapshaper)
```
 
 # Read in Data 
 
```{r Read in Data, include=T}
 all_mfri = list.files('./Wildfire_MFRI2/',pattern = '.tif',full.names = T)
 for(file in all_mfri){
   object_name = file_path_sans_ext(basename(file))
   assign(object_name, raster(file))
 }

CC4a_reg = read_sf('./Boundries/CC4a_RegionsSub.shp')
CC4a_reg  = st_transform(CC4a_reg, "+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
# dissolve multipart Sierra Mountain feature
CC4a_reg = ms_dissolve(CC4a_reg,field = 'Region')

```

# Plot PLOS1 human natural effects 

```{r , include=T}
hum_ef = raster('Human_Nat_Effect/hum_effect.tif')
hum_ef_df = data.frame(rasterToPoints(hum_ef))

for(region_aoi in CC4a_reg$Region[7]){  
    aoi = st_bbox(CC4a_reg[CC4a_reg$Region==region_aoi,])
    aplot = ggplot()+  geom_raster(data=hum_ef_df,aes(x=x,y=y,fill=hum_effect))+ 
     scale_fill_gradientn(colours= rev(c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" )),  
        limits=c())+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) +  
     #ggtitle(paste(region_aoi,'\nChange in MFRIs 2000 - 2025 \nMean model run'))+
      coord_sf( xlim=c(aoi[1],aoi[3]),ylim=c(aoi[2],aoi[4]) )+ labs(fill='Human Effect\non Fire Count') 
    plot(aplot)
}
ggsave(filename = 'C://Users/mmann/Desktop/human_eff_sf.png')



nat_ef = raster('Human_Nat_Effect/nat_effect.tif')
nat_ef_df = data.frame(rasterToPoints(nat_ef))

for(region_aoi in CC4a_reg$Region[7]){  
    aoi = st_bbox(CC4a_reg[CC4a_reg$Region==region_aoi,])
    aplot = ggplot()+  geom_raster(data=nat_ef_df,aes(x=x,y=y,fill=nat_effect))+ 
     scale_fill_gradientn(colours= rev(c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" )),  
        limits=c())+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) +  
     #ggtitle(paste(region_aoi,'\nChange in MFRIs 2000 - 2025 \nMean model run'))+
      coord_sf( xlim=c(aoi[1],aoi[3]),ylim=c(aoi[2],aoi[4]) )+ labs(fill='Natural Effect\non Fire Count') 
    plot(aplot)
}
ggsave('C://Users/mmann/Desktop/natural_eff_sf.png')


pub_ef = raster('Human_Nat_Effect/pub_effect.tif')
pub_ef_df = data.frame(rasterToPoints(pub_ef))

for(region_aoi in CC4a_reg$Region[7]){  
    aoi = st_bbox(CC4a_reg[CC4a_reg$Region==region_aoi,])
    aplot = ggplot()+  geom_raster(data=pub_ef_df,aes(x=x,y=y,fill=pub_effect))+ 
     scale_fill_gradientn(colours= rev(c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" )),  
        limits=c())+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) +  
     #ggtitle(paste(region_aoi,'\nChange in MFRIs 2000 - 2025 \nMean model run'))+
      coord_sf( xlim=c(aoi[1],aoi[3]),ylim=c(aoi[2],aoi[4]) )+ labs(fill='Public Land Effect\non Fire Count') 
    plot(aplot)
}
ggsave('C://Users/mmann/Desktop/public_eff_sf.png')


```


 # Get stats for 01-25 & 26-50  MFRIs  cap at 500 years 
 
```{r Read in MFRIs , include=T}
 all_2001_2025 = stack(all_mfri[grepl('2001_2025',all_mfri)])
 all_2026_2050 = stack(all_mfri[grepl('2026_2050',all_mfri)])
 
 # years for maximum plotted MFRI
 capat=500

 # calculate stats for stacks and cap MFRI 
 # writes out files with 3 different postfix _stat for statisic (mean etc), _df for dataframe for ggplot, _capped for raster capted at value capat
 summary_functions = c('min','max','mean' )
 for(summary in summary_functions){
   for(stac in c('all_2001_2025','all_2026_2050')){
      assign(paste(summary,stac,sep='_'),do.call(summary,list(x=get(stac),na.rm=T)))
      capper = get(paste(summary,stac,sep='_'))
      # write out df for ggplot
      capper.df = data.frame(rasterToPoints(capper))
      names(capper.df)  =c("lon", "lat","MFRI")
      assign(paste(summary,stac,'df',sep='_') ,capper.df)
      # cap at catat yrs
      capper[capper>capat]=capat 
      assign(paste(summary,stac,'capped',sep='_'),capper)
   }}
 
  # write out df for ggplot
  MFRI_76_00.df = data.frame(rasterToPoints(MFRI_76_00))
  names(MFRI_76_00.df)  =c("lon", "lat","MFRI")

```


```{r Plot Stacks, include=T}
all_2001_2025[all_2001_2025>500]=500
all_2026_2050[all_2026_2050>500]=500
plot(all_2001_2025)
plot(all_2026_2050)

```

```{r Plot Change in MFRIs 2000 - 2025 mean, include=T}
 mean_chg_76_25 = MFRI_76_00.df
 mean_chg_76_25$MFRI =  mean_all_2001_2025_df$MFRI-mean_chg_76_25$MFRI
 mean_chg_76_25$MFRI[ mean_chg_76_25$MFRI >350]=350
 rng= range(mean_chg_76_25$MFRI)
 
 ggplot()+geom_raster(data=mean_chg_76_25,aes(x=lon,y=lat,fill=MFRI))+ 
   scale_fill_gradientn(colours= c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" ), #colors in 
      limits=c(-350, 350))+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) + #same limits for plots
   ggtitle('Change in MFRIs 2000 - 2025 mean model run')+coord_sf()
 
 
for(region_aoi in CC4a_reg$Region){  
    aoi = st_bbox(CC4a_reg[CC4a_reg$Region==region_aoi,])
    aplot = ggplot()+  geom_raster(data=mean_chg_76_25,aes(x=lon,y=lat,fill=MFRI))+ 
     scale_fill_gradientn(colours= c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" ),  
        limits=c(-350, 350))+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) +  
     ggtitle(paste(region_aoi,'\nChange in MFRIs 2000 - 2025 \nMean model run'))+
      coord_sf( xlim=c(aoi[1],aoi[3]),ylim=c(aoi[2],aoi[4]) )
    plot(aplot)
    }
``` 
 
```{r Plot Change in MFRIs 2000 - 2050 mean, include=T}
 mean_chg_76_50 = MFRI_76_00.df
 mean_chg_76_50$MFRI =  mean_all_2026_2050_df$MFRI-mean_chg_76_50$MFRI
 mean_chg_76_50$MFRI[ mean_chg_76_50$MFRI >350]=350
 rng= range(mean_chg_76_50$MFRI)
 
 ggplot()+geom_raster(data=mean_chg_76_50,aes(x=lon,y=lat,fill=MFRI))+ 
   scale_fill_gradientn(colours= c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" ),   
                 limits=c(-350, 350))+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75)+  
    ggtitle('Change in MFRIs 2000 - 2050 mean model run')+coord_sf()
 
  
for(region_aoi in CC4a_reg$Region){  
    aoi = st_bbox(CC4a_reg[CC4a_reg$Region==region_aoi,])
    aplot = ggplot()+  geom_raster(data=mean_chg_76_50,aes(x=lon,y=lat,fill=MFRI))+ 
     scale_fill_gradientn(colours= c("#cc0000", "#cc0000"  , 'grey', "#339933","#339933" ),  
        limits=c(-350, 350))+ geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) +  
     ggtitle(paste(region_aoi,'\nChange in MFRIs 2000 - 2050 \nMean model run'))+
      coord_sf( xlim=c(aoi[1],aoi[3]),ylim=c(aoi[2],aoi[4]) )
    plot(aplot)
    }
``` 
 
```{r Extract data to polyons, message=FALSE, warning=FALSE, include=T, paged.print=FALSE}

 the_fun = median  # function used to summarize raster values by polygons
 region_code = data.frame(ID=seq(1,9),as(CC4a_reg,'Spatial')@data$Region)
 full_mean_stack = stack(MFRI_76_00,mean_all_2001_2025,mean_all_2026_2050)
 names(full_mean_stack) =c('2000','2025','2050')
 extract_full_mean_df = extract(full_mean_stack, as(CC4a_reg,'Spatial'), fun=the_fun, na.rm=T, df=T)
 extract_full_mean_df = left_join(region_code,extract_full_mean_df,by='ID') %>% select(-ID)%>%melt()
 extract_full_mean_df$Year = as.numeric(substr(as.character(extract_full_mean_df$variable),2,5))
 names(extract_full_mean_df)=c('Region','variable','value','Year')

 the_fun = min  # function used to summarize raster values by polygons
 full_min_stack = stack(MFRI_76_00,min_all_2001_2025,min_all_2026_2050)
 names(full_min_stack) =c('2000','2025','2050')
 extract_full_min_df = extract(full_min_stack, as(CC4a_reg,'Spatial'), fun=the_fun, na.rm=T, df=T)
 extract_full_min_df = left_join(region_code,extract_full_min_df,by='ID') %>% select(-ID)%>%melt()
 extract_full_min_df$Year = as.numeric(substr(as.character(extract_full_min_df$variable),2,5))
 names(extract_full_min_df)=c('Region','variable','value','Year')

```
  
```{r Plot MFRI time series by region MIN, message=FALSE, warning=FALSE, include=T}
  ggplot()+geom_smooth(data=subset(extract_full_min_df, Region != 'Inland South' ),aes(x=Year,y=value,color=Region,group=Region),size=1.25,alpha=.6)  +ggtitle('Minimum observed MFRI of Min(all_models) by region - \n omitting Inland South')
 
```
 
```{r Plot MFRI time series by region MEDIAN of MEAN, message=FALSE, warning=FALSE, include=T}
  ggplot()+geom_smooth(data=subset(extract_full_mean_df, Region != 'Inland South' ),aes(x=Year,y=value,color=Region,group=Region),size=1.25,alpha=.6)  +ggtitle('Median observed MFRI of Mean(all_models) by region - \n omitting Inland South')
 
```
 

# Median MFRI by individual model run 
```{r Extract individual models to polyons, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}

  the_fun = median
  for(model in c('GA2','MIROC_rcp45','MIROC_rcp85','mpircp','PA2')){
    region_code = data.frame(ID=seq(1,9),as(CC4a_reg,'Spatial')@data$Region)

    model_stack = stack(MFRI_76_00,all_2001_2025[[grep(model,names(all_2001_2025))]],
                        all_2026_2050[[grep(model,names(all_2001_2025))]])
    names(model_stack) =c('2000','2025','2050')
    extract_model_stack_df = extract(model_stack, as(CC4a_reg,'Spatial'), fun=the_fun, na.rm=T, df=T)
    extract_model_stack_df = left_join(region_code,extract_model_stack_df,by='ID') %>% select(-ID)%>%melt()
    extract_model_stack_df$Year = as.numeric(substr(as.character(extract_model_stack_df$variable),2,5))
    names(extract_model_stack_df)=c('Region','variable','value','Year')
    
    aplot = ggplot()+geom_smooth(data=subset(extract_model_stack_df, Region != 'Inland South' ),     aes(x=Year,y=value,color=Region,group=Region),size=1.25,alpha=.6)  +ggtitle(paste(model,' - Median observed MFRI by region - \n omitting Inland South'))  
    plot(aplot)
  }
```



<!-- ```{r Plot MFRIs, eval=FALSE, include=FALSE} -->
<!--  all_2001_2025 = stack(all_mfri[grepl('2001_2025',all_mfri)]) -->
<!--  all_2026_2050 = stack(all_mfri[grepl('2026_2050',all_mfri)]) -->
<!--  capat=1e14 -->
<!--  summary_functions = c('min','max','mean' ) -->
<!--  for(summary in summary_functions){ -->
<!--    for(stac in c('all_2001_2025','all_2026_2050')){ -->
<!--       assign(paste(summary,stac,sep='_'),do.call(summary,list(x=get(stac),na.rm=T))) -->
<!--       capper = get(paste(summary,stac,sep='_')) -->
<!--       capper[capper>capat]=capat # cap at 500 yrs -->
<!--       assign(paste(summary,stac,sep='_'),capper) -->
<!--    }} -->


<!--   plot(min_all_2026_2050) -->
<!--   MFRI_76_00[MFRI_76_00>500]=500 -->
<!--   plot(MFRI_76_00) -->
<!-- ``` -->


