---
title: "Fire Visualizations"
date: "March 3, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
# fire time series
library(plyr)
library(dplyr)
library(tidyr)
library(broom)
library(ggplot2)
```


 
```{r echo=T, message=F, warning=F }
# read in data
setwd('./bayarea/')
l1r45 <- read.csv('./rcp45-low.csv',as.is=T)
l2r45 <- read.csv('./rcp45-central.csv',as.is=T)
l3r45 <- read.csv('./rcp45-high.csv',as.is=T)
l1r85 <- read.csv('./rcp85-low.csv',as.is=T)
l2r85 <- read.csv('./rcp85-central.csv',as.is=T)
l3r85 <- read.csv('./rcp85-high.csv',as.is=T)

# set up
baf <- rbind(l1r45,l2r45,l3r45,l1r85,l2r85,l3r85)
dim(baf)

head(baf)
baf$year <- as.numeric(substr(baf$date,4,7))
 
#scenario groups
baf$pop_recode = revalue(baf$population, c("L_mu"="Low", "bau_mu"="BAU",'H_mu'='High'))
baf$scen_pop = paste(baf$scenario,baf$pop_recode,sep='_')
baf$model_scen_pop = paste(baf$name, baf$scenario,baf$pop_recode,sep='_')
baf$model = baf$name

# reorder population factor
baf$pop_recode = ordered(baf$pop_recode, levels = c("Low", "BAU", "High"))

```

```{r}
  # download all from http://cal-adapt.org/data/
  
  # # unzip everything
  # setwd('C:/Users/mmann/Downloads/')
  # ziped = list.files('.',pattern='.zip',full.names = T)
  # for(file_zip in ziped){
  #   unzip(file_zip,exdir=tools::file_path_sans_ext(file_zip)) 
  # }
  # 
  # list.of.files <- list.files('C:/Users/mmann/Downloads/', ".tif$",recursive = T, full.names = T)
  # file.copy(list.of.files, to = 'C:/Users/mmann/Desktop/CA_Wildfire_CMIP5/Westerling_Fire_Runs/',overwrite = T)    

  decade_group_names = list(c(1976,2000), c(2001,2025), c(2026,2050),c(2051,2075),c(2076,2100))
  # model_abrev = c("CanESM2","CNRM-CM5","HadGEM2-ES","MIROC5" )
  # pop_scenario = c('bau') #,'L','H')
  # scenario = c(45,85)
   
  fire_tif = data.frame(fire_tif=list.files('C:/Users/mmann/Desktop/CA_Wildfire_CMIP5/Westerling_Fire_Runs/',
                                            pattern='.tif', full.names = T),stringsAsFactors = F )

  # calculate average burned area for base year 
  search_range = paste(seq(decade_group_names[[1]][1],decade_group_names[[1]][2]),collapse='|')
  mean_base_year = fire_tif %>% filter(grepl(search_range,fire_tif))%>% filter(grepl('bau',fire_tif)) %>% .$fire_tif %>% stack() %>% mean(.,na.rm=T)
  
  # create stacks by decade group 
  search_range = paste(seq(decade_group_names[[2]][1],decade_group_names[[2]][2]),collapse='|')
  stack_2001_2025 = fire_tif %>% filter(grepl(search_range,fire_tif))%>% filter(grepl('bau',fire_tif)) %>% .$fire_tif %>% stack()  
  
  search_range = paste(seq(decade_group_names[[3]][1],decade_group_names[[3]][2]),collapse='|')
  stack_2026_2050 = fire_tif %>% filter(grepl(search_range,fire_tif))%>% filter(grepl('bau',fire_tif)) %>% .$fire_tif %>% stack()  
  
  search_range = paste(seq(decade_group_names[[4]][1],decade_group_names[[4]][2]),collapse='|')
  stack_2051_2075 = fire_tif %>% filter(grepl(search_range,fire_tif))%>% filter(grepl('bau',fire_tif)) %>% .$fire_tif %>% stack()  
  
  search_range = paste(seq(decade_group_names[[5]][1],decade_group_names[[5]][2]),collapse='|')
  stack_2076_2100 = fire_tif %>% filter(grepl(search_range,fire_tif))%>% filter(grepl('bau',fire_tif)) %>% .$fire_tif %>% stack() 
  
  # calc differences between future and base year mean 
  dif_2001_2025 = stack_2001_2025-mean_base_year
  dif_2026_2050 = stack_2026_2050-mean_base_year
  dif_2051_2075 = stack_2051_2075-mean_base_year
  dif_2076_2100 = stack_2076_2100-mean_base_year
  
  # convert each model run to 1 for + changes and -1 for - changes
  for(dif_name in ls(envir=.GlobalEnv, pattern="dif_")){
    dif = stack(get(dif_name))
    dif[dif>0]  = 1
    dif[dif==0] = 0
    dif[dif<0]  = -1
    assign(dif_name,dif)
  }
  rm(dif_name)
  
  # find models that agree 
  threshold = 150 
  for(dif_name in ls(envir=.GlobalEnv, pattern="dif_")){
    print(dif_name)
    sum_s =  sum(stack(get(dif_name)))
    agg_s = sum_s
    agg_s[!is.na(agg_s)] = 0
    agg_s[sum_s>threshold]  = 1
    agg_s[sum_s<-1*threshold]  = -1
    assign(paste('agree',dif_name,sep='_'),agg_s)
  }
  rm(dif_name)

  
    
  ggplot() + geom_raster(data=na.omit(Agreement_2026_2050), aes(x=x, y=y, fill=factor(val))) + geom_raster(data=na.omit(hum_ef_df), aes(x=x, y=y, fill= factor(hum_effect))) + geom_sf(data=CC4a_reg,colour = "grey30", fill = NA,size=.75) +   coord_sf( xlim=c(aoi[1],aoi[3]),ylim=c(aoi[2],aoi[4]) )+ scale_fill_manual(values = c("#31B404","grey","#DF013A"),name="Agreement")  + labs(fill='Human Effect\non Fire Count') 
  

```


\newpage
## plot by climate and population scenario
```{r echo=T, message=F, warning=F }
# plot by climate and population scenario
ggplot(data=baf, aes(x=year,y=value,group=scen_pop,color=scen_pop))+geom_point(alpha=0.3)+
  geom_smooth(alpha=.5)+geom_smooth(se=F)+ ylab('Area Burned')+xlab('Year') + 
  labs(color='Climate & Population\nScenario')+coord_cartesian(ylim=c(5000,19000))  
```

\newpage
## plot lm models by groups
```{r echo=T, message=F, warning=F }
# plot lm models by groups
ggplot(data=baf, aes(x=year,y=value,group=model_scen_pop,color=model_scen_pop))+
  geom_point(alpha=0.3)+geom_smooth(se = FALSE, method = "lm")+ylab('Area Burned')+
  xlab('Year') + facet_wrap(~model)+labs(color='Climate & Population\nScenario')+  
  coord_cartesian(ylim=c(5000,19000))+theme(legend.position="none")
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data=baf, aes(x=year,y=value,group=model_scen_pop,color=model_scen_pop))+
  geom_point(alpha=0.3)+geom_smooth(se = FALSE, method = "lm")+ylab('Area Burned')+
  xlab('Year') + facet_wrap(~pop_recode)+labs(color='Climate & Population\nScenario')+
  coord_cartesian(ylim=c(5000,19000))+theme(legend.position="none")
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data=baf, aes(x=year,y=value,group=model_scen_pop,color=model_scen_pop))+
  geom_point(alpha=0.3)+geom_smooth(se = FALSE, method = "lm")+ylab('Area Burned')+
  xlab('Year') + facet_wrap(~scenario)+labs(color='Climate & Population\nScenario')+
  coord_cartesian(ylim=c(5000,19000))+theme(legend.position="none")
```
\newpage

##Calculate regression coefficients
```{r echo=T, message=F, warning=F }
# get regression coefficients
baf_reg = baf %>% group_by(model,scenario, pop_recode) %>% do(fit = lm(value~year, data = .))
baf_coef = tidy(baf_reg, fit) %>% as.data.frame()
head(baf_coef)

# select signficant coefficients
baf_sig = baf_coef  %>% filter(term == "year" & p.value < 0.05) %>% 
  select(model,scenario, pop_recode,estimate )
head(baf_sig)
```
 

##Plot distribution of regression coefficients
```{r echo=T, message=F, warning=F }
ggplot(data = baf_sig)+geom_boxplot(aes(x=model,y=estimate,fill=model))+ 
  labs(fill='Climate\nModel') +ylab(expression(Delta~' Burned Area / Year') )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data = baf_sig)+geom_boxplot(aes(x=scenario,y=estimate,fill=scenario))+ 
  labs(fill='Climate\nScenario') +ylab(expression(Delta~' Burned Area / Year') )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
# fill by climate and population scenaario
ggplot(data = baf_sig)+geom_boxplot(aes(x=model,y=estimate, fill= scenario))+ 
  labs(fill='Climate\nScenario') +ylab(expression(Delta~' Burned Area / Year') )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data = baf_sig)+geom_boxplot(aes(x=model,y=estimate, fill= pop_recode)) + 
  labs(fill='Population\nScenario')+ylab(expression(Delta~' Burned Area / Year') )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
# other versions
ggplot(data = baf_sig)+geom_boxplot(aes(x=scenario,y=estimate,fill=model))+ 
  labs(fill='Climate\nScenario') +ylab(expression(Delta~' Burned Area / Year') )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data = baf_sig)+geom_boxplot(aes(x=scenario,y=estimate,fill=pop_recode))+ 
  labs(fill='Climate\nScenario') + ylab(expression(Delta~' Burned Area / Year') )+
  xlab('Climate Model')

```
 
\newpage

#Calculate maximum burn values
```{r echo=T, message=F, warning=F }
# get regression coefficients
baf_max = baf %>% group_by(model,scenario, pop_recode) %>%   summarize(max = max(value, na.rm = T)) %>% 
  as.data.frame()
head(baf_max)
```


##Plot max burned area
```{r echo=T, message=F, warning=F }
ggplot(data = baf_max)+geom_boxplot(aes(x=model,y=max,fill=model))+ 
  labs(fill='Climate\nModel') +ylab('Maximum Burned Area' )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data = baf_max)+geom_boxplot(aes(x=scenario,y=max,fill=scenario))+ 
  labs(fill='Climate\nScenario') +ylab('Maximum Burned Area')+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
# fill by climate and population scenaario
ggplot(data = baf_max)+geom_boxplot(aes(x=model,y=max, fill= scenario))+ 
  labs(fill='Climate\nScenario') +ylab('Maximum Burned Area' )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data = baf_max)+geom_boxplot(aes(x=model,y=max, fill= pop_recode)) + 
  labs(fill='Population\nScenario')+ylab('Maximum Burned Area' )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
# other versions
ggplot(data = baf_max)+geom_boxplot(aes(x=scenario,y=max,fill=model))+ 
  labs(fill='Climate\nScenario') +ylab('Maximum Burned Area'  )+
  xlab('Climate Model')
```
\newpage
```{r echo=T, message=F, warning=F }
ggplot(data = baf_max)+geom_boxplot(aes(x=scenario,y=max,fill=pop_recode))+ 
  labs(fill='Climate\nScenario') + ylab('Maximum Burned Area')+
  xlab('Climate Model')

```


